valory-xyz/autonolas-registries

test/ServiceRegistry.js
- Removing `only` statement in one of the test files such that all the tests are released.
=> chore: removing only statement to release all the tests

deploy/contracts.js
- Whitelisting updated multisig addresses in the deployment script.
=> chore: adding updated multisig implementation addresses to the deployment script

deploy/contracts.js
- Adding one more service with a service Id 1 to be the default service in the deployment script with 4 agent instances.
=> chore: adding additional first service to the deployment script with 4 agent instances

README.md, scripts/deployment/README.md, scripts/deployment/deploy_06_gnosis_safe_multisig.js, scripts/deployment/gnosis_safe_multisig.json, scripts/deployment/gnosis_safe_same_address_multisig.json
- Use the multisig parameters to deploy the corresponding multisig implementation contract.
=> chore: upgrading multisig implementation script

Dockerfile, entrypoint.sh
- Checking for the passed service config hash in docker.
=> chore: checking for the passed service config hash in docker

README.md
- Adding vulnerabilities list link.
=> doc: adding vulnerabilities list link

.github/workflows/workflow.yaml
=> chore: adding gitleaks into CI

contracts/OperatorWhitelist.sol, contracts/ServiceManagerToken.sol, contracts/ServiceRegistryTokenUtility.sol, contracts/interfaces/IServiceTokenUtility.sol, contracts/test/ERC20Token.sol, contracts/test/MockServiceRegistry.sol, test/OperatorWhitelist.js, test/ServiceManagerToken.js, test/ServiceRegistryTokenUtility.js
- Added `update()` function in the new `ServiceManager` contract;
- Adding tests.
=> Continue the implementation of the service registry with the custom ERC20 token security

.github/workflows/workflow.yaml, hardhat.config.js, package.json, test/AgentRegistry.js, test/ComponentRegistry.js, test/GnosisSafeMultisig.js, test/GnosisSafeSameAddressMultisig.js, test/OperatorWhitelist.js, test/RegistriesManager.js, test/ServiceManager.js, test/ServiceManagerToken.js, test/ServiceRegistry.js, test/ServiceRegistryTokenUtility.js, yarn.lock
- Updating hardhat version and other packages;
- Adjusting tests.
=> chore: updating hardhat version and other packages

audits/internal3/README.md, contracts/utils/OperatorSignedHashes.sol, docs/deployment.md, test/ServiceManagementWithOperatorSignatures.js
- Small refactor as suggested by the internal audit;
- Updated tests.
=> refactor and doc: addressing internal audit findings

deploy/0_deploy.js
- Change `ServiceRegistryL2` manager in the default deploy script.
=> chore: small fix to the default deploy script

deploy/0_deploy.js
- Adding token-related service registry contracts to the default script for local testing.
=> chore: adding token-related service registry contracts to the default script

integrations/solana/contracts/ServiceRegistrySolana.sol
=> Fix transfer error

integrations/solana/scripts/initialize.js
- Minor script change when loading the solana program.
=> chore: minor script change

integrations/solana/scripts/mainnet_service_management.js
- Adding Solana mainnet service deployment script.
=> chore: solana mainnet service deployment script

.gitleaksignore, scripts/audit_chains/audit_contracts_setup.js, scripts/audit_chains/audit_repo_contract.sh
- Adding contract addresses to logs;
- Accounting for local installation of ethereum-source-downloader.
=> chore: optimizing scripts, adding gitleaksignore

CHANGELOG.md, audits/internal2/README.md
=> doc: adding chengelog

CHANGELOG.md
=> chore: updating changelog

contracts/staking/ServiceStaking.sol, contracts/staking/ServiceStakingBase.sol, test/ServiceStaking.js
- Adding tests for service staking.
=> test: Initial testing for staking

audits/internal4/README.md, contracts/staking/MechAgentMod.sol, contracts/staking/ServiceStakingBase.sol, contracts/staking/ServiceStakingMechUsage.sol, contracts/staking/ServiceStakingNativeToken.sol, contracts/staking/ServiceStakingToken.sol, contracts/staking/ServiceStakingTokenMechUsage.sol
=> refactor and chore: addressing internal audit comments

contracts/staking/MechAgentMod.sol, contracts/staking/ServiceStakingMechUsage.sol, contracts/staking/ServiceStakingTokenMechUsage.sol, test/ServiceStaking.js
- Correcting the condition for requests count when interacting with agent mechs.
=> refactor: correct the condition for requests count

.gitleaksignore, contracts/test/ERC20Token.sol, contracts/test/MockTimelock.sol, docs/configuration.json, hardhat.config.js, package.json, scripts/deployment/l2/arbitrum/timelock_send_native_ETH_on_L2.js, scripts/deployment/l2/arbitrum/timelock_token_mint.js, yarn.lock
- Adding arbitrum cross-chain scripts.
=> chore: arbitrum cross-chain scripts

.github/workflows/workflow.yaml, .solcover.js, contracts/staking/ServiceStakingBase.sol, contracts/staking/ServiceStakingFactory.sol, contracts/staking/ServiceStakingNativeToken.sol, contracts/staking/ServiceStakingProxy.sol, contracts/staking/ServiceStakingToken.sol, contracts/staking/ServiceStakingVerifier.sol, contracts/test/MockServiceStaking.sol, hardhat.config.js, package.json, test/ServiceStaking.js, test/ServiceStaking.t.sol, test/ServiceStakingFactory.js, yarn.lock
- Adding staking factory testing;
- Modifying all the service staking tests to work with the proxy approach.
=> Adding staking factory testing

scripts/analyzers/code_line_report.txt
=> final SoCL

audits/README.md, audits/internal6/README.md
=> V1.2.2 internal audit

docs/configuration.json
- adding ETH mainnet staking contract addresses.
=> chore: adding eth staking contract addresses

CHANGELOG.md, README.md
- Adding a tag, updating the changelog.
=> chore and doc: Adding tag, updating the changelog

contracts/utils/ComplementaryServiceMetadata.sol
- Access check is moved into its own view function.
=> refactor: access check is moved into its own view function

.github/workflows/release.yaml, deploy/0_deploy.js, scripts/proposals/proposal_15_staking_verifier_change_limits_set_implementation_arbitrum.js
- Docker image on release - required for open-autonomy.
=> chore: docker image on release - required for open-autonomy
